name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
      - "test-[a-zA-Z0-9]+"

env:
  DOCKER_META_IMAGES: |
    ghcr.io/gomore/imgproxy-base
  DOCKER_META_TAGS: |
    type=semver,pattern=v{{version}}
    type=ref,event=branch,enable=${{ startsWith(github.ref, 'refs/heads/test/') }}

jobs:
  build:
    if: github.repository_owner == 'gomore'
    strategy:
      matrix:
        build:
          - arch: amd64
            dockerPlatform: linux/amd64
            image: macOS-arm64
          - arch: arm64
            dockerPlatform: linux/arm64/v8
            image: macOS-arm64
    runs-on:
      group: ${{ matrix.build.image }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_META_IMAGES }}
          tags: ${{ env.DOCKER_META_TAGS }}
          flavor: |
            latest=auto
            suffix=-${{ matrix.build.arch }},onlatest=true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.build.dockerPlatform }}
          provenance: false
          push: true

  push_manifests:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_META_IMAGES }}
          tags: ${{ env.DOCKER_META_TAGS }}
          flavor: |
            latest=auto

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Push manifests
        run: |
          for tag in ${{ join(fromJSON(steps.meta.outputs.json).tags, ' ') }}
          do
            docker buildx imagetools create -t $tag ${tag}-amd64 ${tag}-arm64
          done
